version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql-prova
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: prova
      MYSQL_PASSWORD: prova
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prova
